Repository 2509-gabaithon/2509-gabaithon, pull requests merged in 2025-09, with the labels that each got.

#4 docs: メンバーを書いた
  README.md
Labels: documentation

#11 tailwindcssをプロジェクト内に適用
  package-lock.json
  package.json
  postcss.config.mjs
  src/app/globals.css
  src/app/page.tsx
Labels: enhancement, フロントエンド

#31 ホーム画面を修正
  src/app/globals.css
  src/app/home/page.tsx
  src/components/HomeScreen.tsx
Labels: フロントエンド

#29 タイマー画面を動くように修正した
  src/app/globals.css
  src/app/timer/page.tsx
  src/components/TimerScreen.tsx
Labels: フロントエンド

#36 スタンプ獲得画面を修正
  src/app/get_stamp/page.tsx
  src/components/StampAcquisitionScreen.tsx
Labels: フロントエンド

#35 マップ画面の修正
  src/app/confirm_location/page.tsx
  src/components/NewLocationCheckScreen.tsx
Labels: フロントエンド

#54 ユーザーネーム入力画面の修正
  src/app/set_user_name/page.tsx
  src/components/NameInputScreen.tsx
Labels: フロントエンド

#53 キャラクター選択・命名画面の修正
  src/app/set_character_name/page.tsx
  src/components/CharacterNameInputScreen.tsx
Labels: フロントエンド

#55 クエスト画面を作成した
  src/app/view_quest/page.tsx
  src/app/view_stamp/page.tsx
  src/components/QuestScreen.tsx
  src/components/StampRallyScreen.tsx
Labels: フロントエンド

#59 クエスト獲得画面のテキストを書き換えた
  src/components/StampAcquisitionScreen.tsx
Labels: フロントエンド

#60 57 inactivate any nav
  src/components/BottomTabNavigation.tsx
  src/components/CharacterDecoScreen.tsx
  src/components/QuestScreen.tsx
Labels: フロントエンド

#58 メインフローの画面遷移をできるようにした
  src/app/page.tsx
Labels: フロントエンド, 優先度：高

#69 ビルドチェックできるようにした
  .github/workflows/ci.yml
Labels: enhancement

#89 スタミナを削除した
  src/components/HomeScreen.tsx
Labels: フロントエンド

#104 現在地チェック画面の地図を画面いっぱいに表示するようにした
  src/components/NewLocationCheckScreen.tsx
Labels: フロントエンド

#115 feat: ユーザープロフィールを更新する処理を実装した
  src/app/page.tsx
  src/utils/supabase/profile.ts
Labels: フロントエンド, バックエンド
